-- Seed data for LITE-stack testing (Kitoboy db + api only, no zoo/models).
--
-- Run against the Kitoboy Postgres database `api`, e.g.:
--   docker compose exec -T db psql -U postgres -d api < scripts/seed.sql
--
-- Table and column names follow the Sequelize models in api/src/db/tables/*.ts
-- (camelCase columns must be double-quoted in Postgres). The `postAttributes`
-- through-table `id` is auto-generated by Sequelize and is omitted here.
--
-- NOTE: this script is derived from the model definitions, not from a live DB.
-- Before running, confirm the exact synced schema once with `\d "postAttributes"`
-- (in particular the auto-id) and adjust if your install differs.
--
-- The api itself seeds statuses (suicide / anti_suicide / not_set) and the UI
-- user on startup. We add `needs_attention` so decision-support has all four.

INSERT INTO "statuses" ("id", "name", "color", "createdAt", "updatedAt")
VALUES ('needs_attention', 'Под наблюдением', '#f59e0b', now(), now())
ON CONFLICT ("id") DO NOTHING;

-- One person
INSERT INTO "persons"
  ("id", "surname", "name", "secondName", "age", "address", "phone",
   "organization", "description", "statusId", "createdAt", "updatedAt")
VALUES
  ('11111111-1111-1111-1111-111111111111', 'Пупкин', 'Василий', 'Иванович',
   '22', 'г.Москва', '+7(999)999-99-99', 'ООО Ромашка', 'тестовая запись',
   'not_set', now(), now());

-- Two avatars for that person (a "public" and an "anonymous" account)
INSERT INTO "avatars"
  ("id", "username", "url", "personId", "statusId", "createdAt", "updatedAt")
VALUES
  ('22222222-2222-2222-2222-222222222222', 'kroko_Gen_04',
   'https://soc.net/kroko_Gen_04', '11111111-1111-1111-1111-111111111111',
   'not_set', now(), now()),
  ('33333333-3333-3333-3333-333333333333', 'vasya_work',
   'https://vk.com/vasya_work', '11111111-1111-1111-1111-111111111111',
   'not_set', now(), now());

-- Attribute classes (names from zoo/config/mapping.yml; real ids are UUIDs)
INSERT INTO "attributes" ("id", "name", "color", "createdAt", "updatedAt")
VALUES
  ('a0000001-0000-0000-0000-000000000001',
   'клинические проявления/депрессия', '#ffffff', now(), now()),
  ('a0000002-0000-0000-0000-000000000002',
   'деструктивное поведение/самоповреждение', '#ffffff', now(), now()),
  ('a0000003-0000-0000-0000-000000000003',
   'номер телефона', '#ffffff', now(), now());

-- Posts for kroko_Gen_04
INSERT INTO "posts" ("id", "text", "postedAt", "avatarId", "createdAt", "updatedAt")
VALUES
  ('b0000001-0000-0000-0000-000000000001',
   'сегодня опять не вижу смысла вставать', '2025-04-10T12:38:22.922Z',
   '22222222-2222-2222-2222-222222222222', now(), now()),
  ('b0000002-0000-0000-0000-000000000002',
   'гуляли с друзьями, было неплохо', '2025-04-11T09:15:44.101Z',
   '22222222-2222-2222-2222-222222222222', now(), now());

-- ML labels: link the first post to depression + self-harm classes.
INSERT INTO "postAttributes" ("postId", "attributeId", "createdAt", "updatedAt")
VALUES
  ('b0000001-0000-0000-0000-000000000001',
   'a0000001-0000-0000-0000-000000000001', now(), now()),
  ('b0000001-0000-0000-0000-000000000001',
   'a0000002-0000-0000-0000-000000000002', now(), now());
